### ISSUE TITLE
Error when updating value in a large lowdb instance

### ISSUE THREAD

**Issue by samuelstein** [typicode/lowdb#180]
hello,
i have a problem when i try to update a value in lowdb. my instance is based on a ~150 MB database file which results in ~800 MB memory usage and i use the filesync storage adapter.

my update code is:
`db.getValue(sheetName, col, row).assign({
		value: newValue
	}).write()`

**explanation:** my json file has a spreadsheet structure (sheets, rows, cells). _db.getValue()_ is a mixin which searchs a sheet in my json file and updates a value in a cell.

the problem is that i get an exception when i try to update a cell with the code above. 
the exception is: 
`RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at stringify (/home/samuelstein/WORK/projects/Parametrierung/node_modules/lowdb/lib/storages/_json.js:8:17)
    at Object.fileSyncWrite [as write] (/home/samuelstein/WORK/projects/Parametrierung/node_modules/lowdb/lib/storages/file-sync.js:34:16)
    at LodashWrapper.db.write (/home/samuelstein/WORK/projects/Parametrierung/node_modules/lowdb/lib/common.js:35:24)
    at LodashWrapper.<anonymous> (/home/samuelstein/WORK/projects/Parametrierung/node_modules/lowdb/lib/main.js:22:15)
    at apply (/home/samuelstein/WORK/projects/Parametrierung/node_modules/lodash/lodash.js:495:27)
    at LodashWrapper.wrapper [as write] (/home/samuelstein/WORK/projects/Parametrierung/node_modules/lodash/lodash.js:5356:16)`

Maybe you have an idea how to solve this issue?

**Comment by typicode** [comment]
Hmm right now, no idea but it has been raised on JSON Server
https://github.com/typicode/json-server/issues/529

And here too
https://github.com/typicode/json-server/issues/529

Maybe I would try to create a custom adapter for large files, like

```js
function write (obj) {
  Object.keys(obj).forEach((key) => {
    const data = obj[key]
    const str = JSON.stringify(data, null, 2)
    fs.writeFileSync(`${key}.json`, str)
  }
}
```

This is some very naive code, quickly written, but the idea would be to split the different parts of your big objects into smaller parts that would be stringified and written to different files.
https://github.com/typicode/lowdb#how-to-use-a-custom-storage-or-format

Obviously, you would have to create a special read function to merge them back.

**Comment by samuelstein** [comment]
I also thought about that. I got a litte deeper into the writing function of lowdb.  
When updating a value it seems to me that the whole json will be stringified and then persisted. is that really neccessary?  
I'm not so java script familiar but what would be if the writing partially updates a value or uses [JSONStream](https://github.com/dominictarr/JSONStream) lib functionality?
