### ISSUE TITLE
_.last is not working

### ISSUE THREAD

**Issue by axi92** [typicode/lowdb#183]
Can is use this from lodash?
_.last is not working =(

```
var top_10 = db.get('done')
		.map('username')
		.countBy()
		.toPairs()
		.sortBy(_.last)
		.reverse()
		.take(5)
		.map(_.head)
		.value();
```

**Comment by typicode** [comment]
Hi @axi92,

Hmm, not sure why. Have you tried logging to maybe get a better understanding of this part?

```js
var top_10 = db.get('done')
		.map('username')
		.countBy()
		.toPairs()
		.sortBy(item => { console.log(item, _.last(item)); return _.last(item))
		.reverse()
		.take(5)
		.map(_.head)
		.value();
```

**Comment by axi92** [comment]
@typicode 
```
var top_10 = db.get('done')
		.map('username')
		.countBy()
		.toPairs()
		.sortBy(item => { console.log(item, _.last(item)) ; return _.last(item) })
		.reverse()
		.take(5)
		.map(_.head)
		.value();
```

OP:
```
13:24:28 ~: ReferenceError: _ is not defined
    at Object.<anonymous> (C:\Users\axi92\Documents\opr-fail_bot\index.js:197:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by axi92** [comment]
Ty the first one solved it \o/
No I am just using it with the db.
