### ISSUE TITLE
db.get is not a function

### ISSUE THREAD

**Issue by natsu90** [typicode/lowdb#219]
Hi, I'm following this code sample, https://github.com/typicode/lowdb/tree/master/examples#server, but it give me below error;

```
TypeError: db.get is not a function
    at /Users/sulaiman/Workspace/malique/server/api.js:29:18
    at Layer.handle [as handle_request] (/Users/sulaiman/Workspace/malique/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/sulaiman/Workspace/malique/server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/sulaiman/Workspace/malique/server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/sulaiman/Workspace/malique/server/node_modules/express/lib/router/layer.js:95:5)
    at /Users/sulaiman/Workspace/malique/server/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/sulaiman/Workspace/malique/server/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/sulaiman/Workspace/malique/server/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/sulaiman/Workspace/malique/server/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/sulaiman/Workspace/malique/server/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by hgcummings** [comment]
In the example as-written, db is undefined. From your stack trace it looks like you've avoided this issue. However, db may still be a Promise, in which case you need to resolve it before calling .get().

I've raised PR #223 to make this less confusing.
