### ISSUE TITLE
decrypt data error

### ISSUE THREAD

**Issue by chitao5799** [typicode/lowdb#383]
Hi !
I try to run the example encryption like follow:
```javascript
fileName: file2.js
//-------------
6           const low = require('lowdb');
7           const FileSync = require('lowdb/adapters/FileSync');
8           const adapter = new FileSync('db.json', {
9                  serialize: (data) => encrypt(JSON.stringify(data)),
10                deserialize: (data) => JSON.parse(decrypt(data))
11          });
12         const db = low(adapter);
            db.defaults({ duLieu: [] }).write();
```
but I get the following error:

```javascript
E:\...\node_modules\lowdb\adapters\FileSync.js:42
          throw e;
          ^

ReferenceError: decrypt is not defined
    at FileSync.deserialize (E:\...\file2.js:10:37)
    at FileSync.read (E:\...\node_modules\lowdb\adapters\FileSync.js:37:30)
    at LodashWrapper.db.read (E:\...\node_modules\lowdb\lib\main.js:32:21)
    at module.exports (E:\...\node_modules\lowdb\lib\main.js:51:13)
    at Object.<anonymous> (E:\...\file2.js:12:12)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
```
 lowdb version:       "lowdb": "^1.0.0",
node version:  v12.13.1

Thank you

**Comment by angeal185** [comment]
you have to add your own encrypt/decrypt functions.

for example:

```js
const crypto = require('crypto'),
low = require('lowdb'),
FileSync = require('lowdb/adapters/FileSync');

const enc = {
  defaults: {
    cipher: 'aes',
    bit_len: '256',
    iv_len: 32,
    tag_len: 16,
    encode: 'hex',
    digest: 'sha512'
  },
  encrypt: function (text, key){
   try {
     const iv = crypto.randomBytes(enc.defaults.iv_len),
     cipher = crypto.createCipheriv(
       [enc.defaults.cipher, enc.defaults.bit_len, 'gcm'].join('-'),
       Buffer.from(key, enc.defaults.encode),
       iv
     ),
     encrypted = Buffer.concat([cipher.update(text, 'utf8'), cipher.final()]);
     return Buffer.concat([iv, cipher.getAuthTag(), encrypted]).toString(enc.defaults.encode);
   } catch (err) {
     if(err){return console.error(err)}
   }
 },
 decrypt: function (encdata, key){
   try {
     let tag_slice = enc.defaults.iv_len + enc.defaults.tag_len;
     encdata = Buffer.from(encdata, enc.defaults.encode);
     const decipher = crypto.createDecipheriv(
       [enc.defaults.cipher, enc.defaults.bit_len, 'gcm'].join('-'),
       Buffer.from(key, enc.defaults.encode),
       encdata.slice(0, enc.defaults.iv_len)
     );
     decipher.setAuthTag(encdata.slice(enc.defaults.iv_len, tag_slice));
     return decipher.update(encdata.slice(tag_slice), 'binary', 'utf8') + decipher.final('utf8');
   } catch (err) {
     if(err){return console.error(err)}
   }
 },
 keygen: function(len, iter){
   return crypto.pbkdf2Sync(
     crypto.randomBytes(len),
     crypto.randomBytes(len),
     iter, len, enc.defaults.digest
   ).toString(enc.defaults.encode)
 }
}

// enc.keygen(32, 10000)
// dont use this key!
const crypt_key = '5db6aac5236daabc85703f3238563101cd1cfd9fb15e3db5352ca68169fa0877';

const adapter = new FileSync('db.json', {
  serialize: function(obj){
    return enc.encrypt(JSON.stringify(obj), crypt_key)
  },
  deserialize: function(data){
    return JSON.parse(enc.decrypt(data, crypt_key))
  }
}),
db = low(adapter);
 
```

**Comment by typicode** [comment]
Thanks for the detailed solution @angeal185 :)
