### ISSUE TITLE
Cannot find module \node_modules\lowdb\lib\adapters\JSONFile

### ISSUE THREAD

**Issue by iwxfer** [typicode/lowdb#463]
I am just trying the example in readme, but not working

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\dev\maylin\js\node_modules\lowdb\lib\adapters\JSONFile' imported from C:\dev\maylin\js\node_modules\lowdb\lib\index.js
    at finalizeResolution (internal/modules/esm/resolve.js:276:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:88:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

**Comment by typicode** [comment]
Thanks for the report :+1:  Should be good in v2.0.2, feel free re-open otherwise :)
