### ISSUE TITLE
TypeScript: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by GliderCodes** [typicode/lowdb#482]
I am trying this library in TypeScript and I can't find a way to make it work.

```typescript
// file database.ts
import { Low, JSONFile } from 'lowdb'
import { join } from 'path'

/** database path */
const db_path = join(__dirname, '../utils/database/db.json');

export type DatabaseType = {
    guilds: {}
    cache: {} 
}

/** database class to initialize the client database */
class Database {
    /** main database, use this to access the db */
    db: Low<DatabaseType>
    /** client based cache */
    public cache: Cache

    constructor(public bot: Client) {
        const adapter = new JSONFile<DatabaseType>(db_path)
        this.db = new Low<DatabaseType>(adapter);
        this.cache = this.db.data.cache;
        this.initialize()
    }

    /** initialize the database */
    private initialize() {
        this.db.data ||= { guilds: {}, cache: {} }
    }

    /** returns the full guild object
     * @param id guild id
     */
    public guilds(id: string) {
        return this.db.data.guilds[id];
    }

}

export default Database
```
I try to import this via 
```typescript
import Database from './database`
```
I get the `[ERR_REQUIRE_ESM]: Must use import to load ES Module` error message. I have tried to see all the possible answers but I am failing to understand the main concept.

```json
// tsconfig.json
{
    "compilerOptions": {
      "module": "commonjs",
      "target": "ES2020",
      "noImplicitAny": false,
      "sourceMap": true,
      "outDir": "build",
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "importHelpers": true,
      "forceConsistentCasingInFileNames": true,
      "resolveJsonModule": true,
      "esModuleInterop": true,
      "lib": [
        "ES2020",
        "esnext.asynciterable"
      ],
      "moduleResolution": "node"
    },
    "exclude": [
      "node_modules"
    ]
  }
  ```
  I have changed the module/lib to `ES2020` yet keep facing the same error. Any help is greatly appreciated. I will provide further specifications: 
  ```
  node: 16.3.0
  npm: 7.15.1
  typescript: 4.2.4
  ts-node-dev: 1.1.6
  ts-node: 9.1.1
   ```
   I have also added `"type":"module"` in `package.json` but I see it not working.

**Comment by typicode** [comment]
I'd try `"module": "ES2020"` in `tsconfig.json`.

There's a very good guide:
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by oschade** [comment]
have the same problem.

**Comment by typicode** [comment]
@oschade please see the guide above

**Comment by ndmgrphc** [comment]
Really wish the ESM only warning were more prominent.  This is a massive undertaking for an existing project.

**Comment by safazi** [comment]
Can't use with coffeescript anymore. Sad!

**Comment by 06000208** [comment]
This made my project no longer run, as it always used require() before this. I realize this is probably on me for not doing my due dilligence when updating lowdb next major version.

**Comment by macizomedia** [comment]
I got to fix the error and make the imports with js but still have another error

```
/home/mmcs/Templates/lowdb_server/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:397
  throw new ERR_PACKAGE_PATH_NOT_EXPORTED(
        ^
Error: ERR_PACKAGE_PATH_NOT_EXPORTED /home/mmcs/Templates/lowdb_server/node_modules/lowdb/ ./lib/adapters/JSONFile /home/mmcs/Templates/lowdb_server/node_modules/lowdb/lib/index.js
    at throwExportsNotFound (/home/mmcs/Templates/lowdb_server/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:397:9)
    at packageExportsResolve (/home/mmcs/Templates/lowdb_server/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:622:3)
    at packageResolve (/home/mmcs/Templates/lowdb_server/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:738:14)
    at moduleResolve (/home/mmcs/Templates/lowdb_server/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:815:18)
    at Object.defaultResolve (/home/mmcs/Templates/lowdb_server/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:929:11)
    at /home/mmcs/Templates/lowdb_server/node_modules/ts-node/src/esm.ts:68:38
    at Generator.next (<anonymous>)
    at /home/mmcs/Templates/lowdb_server/node_modules/ts-node/dist/esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/mmcs/Templates/lowdb_server/node_modules/ts-node/dist/esm.js:4:12)
[nodemon] app crashed - waiting for file changes before starting...
```

I'm using ts-node with a koa server
I did implement the guide above. 

Here is my ts.config 

```
{
  "compilerOptions": {
    "target": "es2017",
    "module": "ESNext",
    "lib": [
      "es6"
    ] ,
    "allowJs": true,
    "outDir": "build",
    "rootDir": "src" ,
    "strict": true ,
    "noImplicitAny": true,
    "moduleResolution": "node",                 
    "esModuleInterop": true,
   
    /* Advanced Options */
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```
Thanks for the Help!
