### ISSUE TITLE
Encrypt example syntax

### ISSUE THREAD

**Issue by m4rky77** [typicode/lowdb#84]
Hi,

I try to run the example encryption with old syntax in this way:

```
var db = low('db.json', {
 format: {
        deserialize: function (str){
        var decrypted = cryptr.decrypt(str);
        var  obj = JSON.parse(decrypted);
        return obj;
    },
        serialize: function(obj) {
        var str = JSON.stringify(obj);
        var encrypted = cryptr.encrypt(str);
        return encrypted;
    }
});

```

but I get the following error:

```
/Users/user/ctacte/node_modules/lowdb/index.js:77
    options.format && Object.assign(db, options.format);
                             ^
TypeError: undefined is not a function
    at low (/Users/user/ctacte/node_modules/lowdb/index.js:77:30)
    at Object.<anonymous> (/Users/user/ctacte/lib/database.js:5:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/user/ctacte/index.js:14:16)
    at Module._compile (module.js:460:26)
```

Is a syntax problem or am I doing something wrong?

Thank you

**Comment by typicode** [comment]
I think your code is OK. What's your version of Node please?

**Comment by m4rky77** [comment]
My node version is v0.12.2.

**Comment by m4rky77** [comment]
I update to v4.2.4 and work fine

**Comment by typicode** [comment]
I've updated lowdb (`v0.11.5`) It should be good now with Node 0.12 too. Thanks for the issue :+1:
