### ISSUE TITLE
TypeError on unsuccessful db.find

### ISSUE THREAD

**Issue by jsayol** [typicode/lowdb#85]
When performing a `.find` operation, if no elements are found an error occurs:

```
node_modules/lowdb/index.js:21
      var v = arg.value ? arg.value() : arg;
                 ^

TypeError: Cannot read property 'value' of undefined
    at LodashWrapper.<anonymous> (node_modules/lowdb/index.js:21:18)
    at LodashWrapper.find (node_modules/lodash/lodash.js:4104:35)
    at Object.<anonymous> (low.js:5:25)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:1003:3
```

**Comment by typicode** [comment]
Thank you for letting me know, it should be better now (`v0.12.1`)
